services:
  - type: web
    name: farm2shop-web
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: singapore
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 10000
